### PR TITLE
Fix span closure time

### PR DESCRIPTION
**Pull request by mpetazzoni**
Closing the span should happen when we're done receiving the answer, not
when we're done sending the request, otherwise the ordering of the trace
is wrong. Previously, it would be CS-CR-SR-SS, instead of CS-SR-SS-CR.

### CODE REVIEW

**Comment by malafeev** [comment]
test failed

**Comment by mpetazzoni** [comment]
Hmm, I need to fix those tests.

**Comment by mpetazzoni** [comment]
So, I got the tests to pass, we were missing some proper handling of `TTransportException` (which is what happens when a `RuntimeException` occurs on the server-side handler).

I was also trying to find a way to call `SpanDecorator.onError` when a normal, declared Thrift exception occurs, but there's no path in `SpanProtocol` where I can see that exception (because the Thrift layer considers this "normal"), so I couldn't make that work. Oh well.

**Comment by malafeev** [comment]
in the catch block client span is not marked as failed (with `ERROR` tag at least, not sure that stack trace is needed). 
```
@Override
  public TMessage readMessageBegin() throws TException {
    try {
      return super.readMessageBegin();
    } catch (TTransportException tte) {
      ActiveSpan span = tracer.activeSpan();
      if (span != null) {
        span.close();
      }
      throw tte;
    }
  }
```

**Pull request merged**
